---
- hosts: web
  tasks:
  - name: execute smple command
    command: echo "This is first line \n this is second line"
    register: result
  - name: print statement for text lines
    debug:
      msg: "{{ result }}"
  - name: get the system uptime
    shell: uptime
    register: result1
  - name: print msg or uptime
    debug:
      var: result1
# this is how you can use variable show output
  - name: print statement
    debug:
      msg: "my system ipadd is {{ ansible_default_ipv4.address }}"


